apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: jobset
    app.kubernetes.io/instance: jobset
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jobset
    app.kubernetes.io/part-of: jobset
  name: jobset-serving-cert
  namespace: openshift-jobset-operator
spec:
  commonName: jobset-webhook
  dnsNames:
  - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc
  - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc.cluster.local
  duration: 8760h
  issuerRef:
    kind: Issuer
    name: jobset-selfsigned-issuer
  renewBefore: 720h
  secretName: webhook-server-cert
  usages:
  - server auth
  - client auth
