apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: jobset
    app.kubernetes.io/instance: jobset
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jobset
    app.kubernetes.io/part-of: jobset
  name: jobset-manager-secrets-rolebinding
  namespace: openshift-jobset-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobset-manager-secrets-role
subjects:
- kind: ServiceAccount
  name: jobset-controller-manager
  namespace: openshift-jobset-operator
